import {
  Calendar,
  MapPin,
  Coffee,
  Gift,
  Music,
  Camera,
  Wifi,
  Car as CarIcon,
  Bus,
  Truck,
  CarTaxiFront as Taxi,
} from "lucide-react";

export const vehicleExamples = {
  "4 + 1(Driver) Seaters": {
    icon: CarIcon,
    description: "Perfect for intimate gatherings and business meetings",
    examples: [
      "Executive business travel",
      "Airport transfers with VIP service",
      "Romantic couple getaways",
      "Family road trips with comfort",
      "City tours with personal guide",
    ],
    features: [
      "GPS Navigation",
      "Leather Seats",
      "Climate Control",
      "Entertainment System",
      "Premium Sound System",
      "Extended Luggage Space",
      "USB Charging Ports",
      "Panoramic Windows",
      "LCD Screens",
    ],
  },
  "12 + 1(Driver) Seaters": {
    icon: Taxi,
    description: "Ideal for medium-sized groups seeking comfort and style",
    examples: [
      "Corporate team outings",
      "Wine tasting tours",
      "Bachelor/Bachelorette parties",
      "Family reunions",
      "Adventure group trips",
    ],
    features: [
      "GPS Navigation",
      "Leather Seats",
      "Climate Control",
      "Entertainment System",
      "Premium Sound System",
      "Extended Luggage Space",
      "USB Charging Ports",
      "Panoramic Windows",
      "LCD Screens",
    ],
  },
  "25 Seaters": {
    icon: Truck,
    description: "Perfect for large groups and special occasions",
    examples: [
      "Destination weddings",
      "Corporate retreats",
      "Sports team transportation",
      "Concert group travel",
      "Multi-family vacation trips",
    ],
    features: [
      "GPS Navigation",
      "Leather Seats",
      "Climate Control",
      "Entertainment System",
      "Premium Sound System",
      "Extended Luggage Space",
      "USB Charging Ports",
      "Panoramic Windows",
      "LCD Screens",
    ],
  },
  "35 Seaters": {
    icon: Bus,
    description: "Designed for large-scale events and group tours",
    examples: [
      "School excursions",
      "Corporate conferences",
      "Tourist groups",
      "Festival transportation",
      "Multi-day tour groups",
    ],
    features: [
      "GPS Navigation",
      "Leather Seats",
      "Climate Control",
      "Entertainment System",
      "Premium Sound System",
      "Extended Luggage Space",
      "USB Charging Ports",
      "Panoramic Windows",
      "LCD Screens",
    ],
  },
};

export const specialPackages = [
  {
    title: "Executive Business Travel",
    icon: Wifi,
    description: "Premium travel solutions for business professionals.",
    features: [
      "Private chauffeur service",
      "Mobile office setup",
      "Priority booking",
      "24/7 concierge service",
      "Corporate billing options",
    ],
  },
  {
    title: "Family Adventure Package",
    icon: Gift,
    description: "Create lasting memories with your loved ones.",
    features: [
      "Child-friendly amenities",
      "Entertainment packages",
      "Flexible scheduling",
      "Family meal options",
      "Educational stop-overs",
    ],
  },
  {
    title: "Luxury Weekend Getaway",
    icon: Coffee,
    description: "Escape in style with our premium weekend packages.",
    features: [
      "Luxury vehicle options",
      "Champagne service",
      "Gourmet catering",
      "Scenic route planning",
      "Hotel booking assistance",
    ],
  },
  {
    title: "Special Events Package",
    icon: Calendar,
    description: "Make your special day truly memorable.",
    features: [
      "Event coordination",
      "Decorated vehicles",
      "Photography service",
      "Custom routes",
      "Group coordination",
    ],
  },
];

export const addOnServices = [
  {
    title: "Professional Photography",
    icon: Camera,
    description: "Capture every moment of your journey.",
    benefits: [
      "Professional photographer",
      "Digital and printed albums",
      "Drone photography",
      "Same-day editing",
      "Social media ready shots",
    ],
  },
  {
    title: "Entertainment Package",
    icon: Music,
    description: "Keep the party going with premium entertainment.",
    benefits: [
      "Karaoke system",
      "Gaming consoles",
      "Premium sound system",
      "Streaming services",
      "Party lighting",
    ],
  },
  {
    title: "Guided Tours",
    icon: MapPin,
    description: "Explore with knowledgeable local experts.",
    benefits: [
      "Certified local guides",
      "Customized itineraries",
      "Historical insights",
      "Hidden gem locations",
      "Interactive experiences",
    ],
  },
];
